export type Area =
  | "Downtown"
  | "Third Ward / Harbor"
  | "East Side"
  | "West Milwaukee"
  | "North Shore"
  | "Waukesha County"
  | "Lake Country"
  | "South / Racine"
  | "Lake Geneva";

export type VenueType =
  | "Hotel"
  | "Historic hall"
  | "Industrial loft"
  | "Museum / mansion"
  | "Barn"
  | "Country club"
  | "Brewery / unique"
  | "Banquet hall";

export type Venue = {
  id: string;
  name: string;
  city: string;
  area: Area;
  type: VenueType;
  address: string;
  maxGuests: number;
  capacity: string;
  indoor: string;
  website: string;
  phone: string;
  notes: string;
  price: string;
};

export const START_HERE = [
  "pfister",
  "saint-kate",
  "turner-hall",
  "grain-exchange",
  "mam",
  "pritzlaff",
  "rivulet",
  "factory-barclay",
  "best-place",
  "courthouse-1893",
  "rustic-manor",
  "greenhouse-7",
] as const;

export const VENUES: Venue[] = [
  {
    id: "pfister",
    name: "The Pfister Hotel",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "424 E Wisconsin Ave",
    maxGuests: 600,
    capacity: "Rouge 120; Imperial 300–350; Grand up to ~600 seated",
    indoor: "Three indoor ballrooms plus Grand Foyer for ceremony-to-reception flip",
    website: "https://www.thepfisterhotel.com/gatherings/weddings/wedding-venues/",
    phone: "414-390-3802",
    notes: "1893 Victorian landmark; rooms, spa, and Mason Street Grill on site",
    price: "Knot avg ~$22k; ceremony from $1,500; entrees $65–$140",
  },
  {
    id: "hilton-mke",
    name: "Hilton Milwaukee",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "509 W Wisconsin Ave",
    maxGuests: 700,
    capacity: "Empire ~250 seated; Crystal up to ~500–700; hotel lists 100–700",
    indoor: "Art Deco Crystal and Empire ballrooms; 2025 renovation; patio with indoor backup",
    website: "https://www.hilton.com/en/hotels/mkemhhf-hilton-milwaukee-city-center/",
    phone: "414-271-7250",
    notes: "Skywalk to Baird Center; on-site rooms and catering",
    price: "Pricing on request; 22% service charge",
  },
  {
    id: "saint-kate",
    name: "Saint Kate – The Arts Hotel",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "139 E Kilbourn Ave",
    maxGuests: 420,
    capacity: "Dada ~200; ARC Theatre ~96–125; Simone Ballroom up to ~420 seated",
    indoor: "Boutique arts-hotel ballrooms and theater",
    website: "https://www.saintkatearts.com/weddings",
    phone: "414-276-8686",
    notes: "Can host shower through reception in one building",
    price: "F&B $54–$120; 24% service; outside catering extra",
  },
  {
    id: "marriott-downtown",
    name: "Milwaukee Marriott Downtown",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "323 E Wisconsin Ave",
    maxGuests: 320,
    capacity: "About 300 seated / 450 standing",
    indoor: "Hotel ballroom event space",
    website: "https://www.marriott.com/en-us/hotels/mkeap-milwaukee-marriott-downtown/overview/",
    phone: "414-278-5999",
    notes: "Downtown hotel; confirm named rooms on a tour",
    price: "On request; 25% service charge",
  },
  {
    id: "westin",
    name: "The Westin Milwaukee",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "550 N Van Buren St",
    maxGuests: 293,
    capacity: "About 293 seated / 366 standing",
    indoor: "Hotel ballroom",
    website: "https://www.marriott.com/en-us/hotels/mkewe-the-westin-milwaukee/overview/",
    phone: "414-224-5224",
    notes: "Newer downtown hotel option",
    price: "Entrees $35–$50; 25% service charge",
  },
  {
    id: "iron-horse",
    name: "Iron Horse Hotel",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Hotel",
    address: "500 W Florida St",
    maxGuests: 175,
    capacity: "Up to 175",
    indoor: "Boutique hotel event space in Walker’s Point",
    website: "https://www.theironhorsehotel.com/",
    phone: "414-374-4766",
    notes: "Industrial-chic hotel; good if you want rooms next door",
    price: "Entrees $45–$69; 21% service charge",
  },
  {
    id: "hotel-metro",
    name: "Hotel Metro",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "411 E Mason St",
    maxGuests: 75,
    capacity: "75 seated / 90 standing",
    indoor: "Intimate Art Deco hotel rooms",
    website: "https://hotelmetro.com/",
    phone: "414-272-1937",
    notes: "Best for a small indoor wedding, not a large reception",
    price: "Entrees $42–$75; 21% service charge",
  },
  {
    id: "turner-hall",
    name: "Turner Hall Ballroom",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "1040 N Vel R. Phillips Ave",
    maxGuests: 300,
    capacity: "Flexible seating up to ~300; some lists say 400",
    indoor: "Two-story 7,000+ sq ft National Historic Landmark ballroom with balcony",
    website: "https://www.turnerhallballroomweddings.com/",
    phone: "414-242-8143",
    notes: "Choose-your-own caterer; in-house bar; concert lighting/sound",
    price: "On request",
  },
  {
    id: "grain-exchange",
    name: "The Grain Exchange",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "225 E Michigan St",
    maxGuests: 350,
    capacity: "300 with dance floor; 350 seated; 500 cocktail",
    indoor: "Three-story historic trading floor in the Mackie Building",
    website: "https://www.bartolottas.com/catering/venues/grain-exchange",
    phone: "414-727-6980",
    notes: "Bartolotta exclusive catering; frescoes and soaring ceilings",
    price: "Entrees $35–$60; 24% service charge",
  },
  {
    id: "mam",
    name: "Milwaukee Art Museum",
    city: "Milwaukee",
    area: "Downtown",
    type: "Museum / mansion",
    address: "700 N Art Museum Dr",
    maxGuests: 400,
    capacity: "Windhover Hall often cited ~400 seated; Mag lists up to 1,000",
    indoor: "Quadracci Pavilion, Windhover Hall, gallerias, café, auditorium",
    website: "https://mam.org/info/rentals/",
    phone: "414-224-3287",
    notes: "Calatrava architecture; Burke Brise Soleil; in-house catering",
    price: "Rental often $7k–$20k; Knot from ~$12,500; entrees $75–$100",
  },
  {
    id: "discovery-world",
    name: "Discovery World",
    city: "Milwaukee",
    area: "Downtown",
    type: "Museum / mansion",
    address: "500 N Harbor Dr",
    maxGuests: 700,
    capacity: "Pilot House ~280–400 seated; Pavilion up to ~400–700 seated",
    indoor: "Pilot House, Pavilion, Great Lakes exhibit, Reiman Aquarium",
    website: "https://bartolottas.com/discoveryworld",
    phone: "414-765-8610",
    notes: "Lakefront science museum; Bartolotta exclusive caterer",
    price: "On request",
  },
  {
    id: "harley",
    name: "Harley-Davidson Museum (1903 Events)",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Museum / mansion",
    address: "400 W Canal St",
    maxGuests: 420,
    capacity: "About 420 seated / 550 standing",
    indoor: "Multiple indoor campus spaces (outdoor campus also available)",
    website: "https://www.1903events.com/",
    phone: "414-287-2789",
    notes: "Museum admission often included; parking on campus",
    price: "On request",
  },
  {
    id: "mpm",
    name: "Milwaukee Public Museum",
    city: "Milwaukee",
    area: "Downtown",
    type: "Museum / mansion",
    address: "800 W Wells St",
    maxGuests: 400,
    capacity: "Receptions often up to ~400; Mag lists a much wider range",
    indoor: "Steigleder Gallery plus exhibit spaces; Zilli catering",
    website: "https://www.mpm.edu/",
    phone: "414-278-2728",
    notes: "Magazine 2026 guide says the museum closes January 2027 — confirm before touring",
    price: "On request",
  },
  {
    id: "pritzlaff",
    name: "The Historic Pritzlaff",
    city: "Milwaukee",
    area: "Downtown",
    type: "Industrial loft",
    address: "333 N Plankinton Ave",
    maxGuests: 600,
    capacity: "333: 100–600; combined building up to ~1,000",
    indoor: "Two industrial halls (333 and 325) plus courtyard; ~28,000 sq ft",
    website: "https://pritzlaffevents.com/space-333/",
    phone: "414-433-6088",
    notes: "Zilli Hospitality; cream city brick, mezzanine, walk-in vault",
    price: "Ask for pricing guide",
  },
  {
    id: "loft-broadway",
    name: "The Loft On Broadway",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "177 N Broadway",
    maxGuests: 200,
    capacity: "Up to ~200 seated / 250 cocktail",
    indoor: "Third-floor 1893 loft with cream city brick and wood beams",
    website: "https://theloftonbroadway.com/",
    phone: "414-481-1552",
    notes: "Sister venue to Factory on Barclay; Saz’s often listed as caterer",
    price: "Not published",
  },
  {
    id: "rivulet",
    name: "The Rivulet",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "309 N Water St",
    maxGuests: 225,
    capacity: "About 200–250 seated",
    indoor: "Indoor main hall with brick, timber, grand staircase; Riverwalk patio add-on",
    website: "https://www.rivuletmke.com/",
    phone: "414-587-7883",
    notes: "Opened 2025; Two Birds Event Group; open catering",
    price: "Knot avg ~$9,500",
  },
  {
    id: "factory-barclay",
    name: "The Factory on Barclay",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "1120 S Barclay St",
    maxGuests: 320,
    capacity: "Banquet up to ~320; full guest count up to ~400",
    indoor: "Main Factory, Warehouse, and Mezzanine in a 1909 industrial building",
    website: "https://thefactoryonbarclay.com/pages/the-space",
    phone: "414-481-1552",
    notes: "Ceremony in Warehouse, reception in Main Factory is a common layout",
    price: "Secondary 2026 guide: rental from ~$8,250",
  },
  {
    id: "ivy-house",
    name: "The Ivy House",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "906 S Barclay St",
    maxGuests: 300,
    capacity: "About 250–300 seated",
    indoor: "Indoor greenery ballroom with cream city brick and skylights",
    website: "https://ivyhousemke.com/",
    phone: "414-539-3339",
    notes: "Two Birds; ivy patio for ceremony with indoor reception backup",
    price: "On request; 24% service charge",
  },
  {
    id: "south-second",
    name: "South Second",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "Walker’s Point (see site)",
    maxGuests: 275,
    capacity: "Indoor up to 275",
    indoor: "Bi-level open loft plus renovated patio",
    website: "https://www.southsecondmke.com/",
    phone: "",
    notes: "Exclusive Saz’s catering; on-site parking",
    price: "Rental page on site; dollars not scraped",
  },
  {
    id: "filament",
    name: "Filament",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "131 W Seeboth St",
    maxGuests: 200,
    capacity: "Up to 200 seated / 250 cocktail",
    indoor: "Historic industrial ballroom with exposed brick and beams",
    website: "https://www.weddingwire.com/biz/filament/34c7163631a45c9d.html",
    phone: "414-587-7883",
    notes: "Two Birds; confirm current booking page — filamentmke.com now points at The Rivulet",
    price: "On request; 22% service charge",
  },
  {
    id: "cooperage",
    name: "The Cooperage",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Industrial loft",
    address: "822 S Water St",
    maxGuests: 175,
    capacity: "150–175 seated / 400 total",
    indoor: "Indoor waterfront event hall",
    website: "https://www.cooperagehall.com/",
    phone: "414-369-2356",
    notes: "Walker’s Point river location",
    price: "Rental $1,500–$6,000",
  },
  {
    id: "gather-deer",
    name: "Gather at the Deer District",
    city: "Milwaukee",
    area: "Downtown",
    type: "Industrial loft",
    address: "Deer District",
    maxGuests: 250,
    capacity: "Up to 250",
    indoor: "Industrial-chic indoor ballroom with attached patio",
    website: "https://gathermke.com/",
    phone: "",
    notes: "Planner roundup favorite for year-round indoor ceremonies",
    price: "Not published",
  },
  {
    id: "fitzgerald",
    name: "The Fitzgerald",
    city: "Milwaukee",
    area: "East Side",
    type: "Museum / mansion",
    address: "1119 N Marshall St",
    maxGuests: 200,
    capacity: "About 200 indoors / 120 courtyard",
    indoor: "1874 Italianate mansion parlors and ballroom",
    website: "https://www.thefitzgeraldmke.com/",
    phone: "",
    notes: "Pabst Theater Group; in-house catering and DJ; formerly listed as Villa Filomena",
    price: "Rental $10k–$15k; entrees $80–$100",
  },
  {
    id: "villa-terrace",
    name: "Villa Terrace",
    city: "Milwaukee",
    area: "East Side",
    type: "Museum / mansion",
    address: "2220 N Terrace Ave",
    maxGuests: 80,
    capacity: "About 80 sit-down / 120 standing",
    indoor: "Indoor villa Great Hall; Renaissance Garden is outdoor add-on",
    website: "https://www.villaterrace.org/",
    phone: "",
    notes: "1920s Italian Renaissance villa; indoor rain plan in the Great Hall",
    price: "Half- and full-day rentals; dollars not published",
  },
  {
    id: "charles-allis",
    name: "Charles Allis Art Museum",
    city: "Milwaukee",
    area: "East Side",
    type: "Museum / mansion",
    address: "1801 N Prospect Ave",
    maxGuests: 150,
    capacity: "120–150",
    indoor: "1911 Tudor mansion: Marble Hall, dining room, and galleries",
    website: "https://www.charlesallis.org/",
    phone: "414-278-8295",
    notes: "Intimate East Side Gold Coast museum wedding",
    price: "On request",
  },
  {
    id: "pabst-mansion",
    name: "Pabst Mansion",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Museum / mansion",
    address: "2000 W Wisconsin Ave",
    maxGuests: 85,
    capacity: "50 sitting / 85 standing",
    indoor: "1892 Gilded Age house museum interiors",
    website: "https://www.pabstmansion.com/",
    phone: "414-931-0808",
    notes: "Small, formal, historic — not a large ballroom",
    price: "Rental $3,500–$8,000",
  },
  {
    id: "society",
    name: "The Society (Milwaukee County Historical Society)",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "910 N Dr. Martin Luther King Jr. Dr",
    maxGuests: 250,
    capacity: "About 200–250 seated",
    indoor: "Restored historic bank: main hall, mezzanine, patio add-on",
    website: "https://www.thesocietymke.com",
    phone: "414-273-8288",
    notes: "Operated with Two Birds Event Group",
    price: "On request",
  },
  {
    id: "best-place",
    name: "Best Place at the Historic Pabst Brewery",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Brewery / unique",
    address: "901 W Juneau Ave",
    maxGuests: 250,
    capacity: "Great Hall 250; Blue Ribbon Hall 150",
    indoor: "Two indoor halls (Great Hall & Speakeasy, Blue Ribbon Hall) plus courtyard",
    website: "https://bestplacemilwaukee.com/rentals/weddings/",
    phone: "414-614-0172",
    notes: "Former Pabst HQ; stained glass, Speakeasy bar, approved caterer list",
    price: "Deposit 25%; published rental dollars on a pricing-info page",
  },
  {
    id: "barley-room",
    name: "The Barley Room at Pabst",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Brewery / unique",
    address: "1125 N 9th St, Suite C",
    maxGuests: 200,
    capacity: "50–200",
    indoor: "Restored 1889 Pabst Bottling House loft",
    website: "https://thebarleyroom.com/",
    phone: "",
    notes: "BYO catering; tables/chairs included; often positioned as more affordable",
    price: "Promos have included ceremony add-ons; ask current 2026–27 rates",
  },
  {
    id: "pilot-project",
    name: "Pilot Project Brewing",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Brewery / unique",
    address: "Brewery District",
    maxGuests: 400,
    capacity: "Room combinations from small to very large (directory max is much higher)",
    indoor: "Beer Hall, Barrel Room, The Venue, Mezzanine",
    website: "https://www.pilotprojectbrewing.com/mkeprivateevents",
    phone: "",
    notes: "Full indoor wedding possible by combining Beer Hall + The Venue",
    price: "WeddingWire often ~$10k start / $15–18k typical",
  },
  {
    id: "greenhouse-7",
    name: "Greenhouse No. 7 at the Mitchell Park Domes",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Brewery / unique",
    address: "Mitchell Park Domes",
    maxGuests: 550,
    capacity: "Up to 550",
    indoor: "Fully indoor greenhouse — garden look without weather risk",
    website: "https://www.milwaukeedomes.org/",
    phone: "",
    notes: "Planner-approved indoor garden venue; glass walls and park views",
    price: "Not published on roundup pages",
  },
  {
    id: "story-hill",
    name: "Story Hill Firehouse",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Brewery / unique",
    address: "407 N Hawley Rd",
    maxGuests: 120,
    capacity: "120 seated / 175 standing",
    indoor: "Restored 1927 firehouse",
    website: "https://storyhillfirehouse.com/",
    phone: "262-477-5813",
    notes: "Original fire poles; unique and relatively intimate",
    price: "On request",
  },
  {
    id: "st-james",
    name: "St. James 1868",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "833 W Wisconsin Ave",
    maxGuests: 275,
    capacity: "75–275",
    indoor: "Historic church property used as an indoor wedding venue",
    website: "https://stjames1868.com/",
    phone: "414-514-5555",
    notes: "Ceremony and reception on site",
    price: "Rental $5,900–$19,000; Knot from ~$7,500",
  },
  {
    id: "tripoli",
    name: "Tripoli Shrine Center",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Historic hall",
    address: "3000 W Wisconsin Ave",
    maxGuests: 400,
    capacity: "Up to 400",
    indoor: "1928 landmark inspired by the Taj Mahal",
    website: "https://www.tripolishrine.org/",
    phone: "414-933-4700",
    notes: "National Register architecture; very distinctive indoor look",
    price: "On request",
  },
  {
    id: "war-memorial",
    name: "War Memorial Center",
    city: "Milwaukee",
    area: "Downtown",
    type: "Brewery / unique",
    address: "750 N Lincoln Memorial Dr",
    maxGuests: 260,
    capacity: "About 260 indoor / Mag lists 300",
    indoor: "Lakefront indoor rooms; outdoor also available",
    website: "https://www.warmemorialcenter.org",
    phone: "414-982-6633",
    notes: "Lake views next to the Art Museum campus",
    price: "On request",
  },
  {
    id: "wisconsin-club-dt",
    name: "Wisconsin Club (downtown)",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "900 W Wisconsin Ave",
    maxGuests: 300,
    capacity: "About 300; Mag lists 500",
    indoor: "Historic private club ballroom (Mirror Image Ballroom)",
    website: "https://wisconsinclub.com/",
    phone: "414-271-7510",
    notes: "Separate from the Wisconsin Club country-club campus on Good Hope Rd",
    price: "On request",
  },
  {
    id: "mac",
    name: "Milwaukee Athletic Club",
    city: "Milwaukee",
    area: "Downtown",
    type: "Hotel",
    address: "758 N Broadway",
    maxGuests: 300,
    capacity: "Up to 300",
    indoor: "1917 downtown club with hotel rooms and indoor event space",
    website: "https://macwi.org/",
    phone: "414-273-5080",
    notes: "Members and nonmembers; rooftop deck is extra, not the only space",
    price: "On request",
  },
  {
    id: "womans-club",
    name: "Woman’s Club of Wisconsin",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "813 E Kilbourn Ave",
    maxGuests: 250,
    capacity: "Up to 250",
    indoor: "Historic clubhouse",
    website: "http://wc-wi.org/",
    phone: "414-276-5170",
    notes: "Classic downtown club setting",
    price: "On request",
  },
  {
    id: "milwaukee-club",
    name: "The Milwaukee Club",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "706 N Jefferson St",
    maxGuests: 150,
    capacity: "100–150",
    indoor: "Private downtown club",
    website: "https://milwaukeeclub.com",
    phone: "414-276-0590",
    notes: "Smaller, formal club wedding",
    price: "Non-member rental about $3,500; 22% service",
  },
  {
    id: "icc",
    name: "Italian Community Center",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Banquet hall",
    address: "631 E Chicago St",
    maxGuests: 600,
    capacity: "600–1,500 depending on rooms",
    indoor: "Large indoor banquet rooms; Bartolotta catering",
    website: "https://www.bartolottas.com/catering/venues/italian-community-center",
    phone: "414-223-2180",
    notes: "Best if you need a large indoor guest count downtown",
    price: "Entrees from $30; 20% service",
  },
  {
    id: "bradley-symphony",
    name: "Bradley Symphony Center",
    city: "Milwaukee",
    area: "Downtown",
    type: "Historic hall",
    address: "212 W Wisconsin Ave",
    maxGuests: 350,
    capacity: "Up to 350",
    indoor: "Restored downtown theater/concert hall event spaces",
    website: "https://www.mso.org/",
    phone: "414-291-6010",
    notes: "Dramatic historic interior",
    price: "Entrees $64–$142; 22% service",
  },
  {
    id: "jan-serr",
    name: "Jan Serr Studio",
    city: "Milwaukee",
    area: "East Side",
    type: "Brewery / unique",
    address: "2155 N Prospect Ave",
    maxGuests: 325,
    capacity: "325 seated / 405 standing",
    indoor: "UWM arts studio / event space",
    website: "https://uwm.edu/arts/rentals/jan-serr-studio",
    phone: "414-256-8765",
    notes: "East Side arts space with high capacity",
    price: "Rental $3,000–$6,500",
  },
  {
    id: "vivarium",
    name: "Vivarium",
    city: "Milwaukee",
    area: "East Side",
    type: "Industrial loft",
    address: "1818 N Farwell Ave",
    maxGuests: 150,
    capacity: "150 seated / 250 cocktail",
    indoor: "Indoor East Side event space (Pabst Theater Group)",
    website: "https://www.vivariummke.com/",
    phone: "414-248-8143",
    notes: "Same operator family as Turner Hall / Fitzgerald",
    price: "Rental $5,000–$10,000",
  },
  {
    id: "public-market",
    name: "Milwaukee Public Market",
    city: "Milwaukee",
    area: "Third Ward / Harbor",
    type: "Brewery / unique",
    address: "400 N Water St",
    maxGuests: 120,
    capacity: "Private rooms; full seated count not clearly published",
    indoor: "Demonstration kitchen and palm garden rooms",
    website: "https://milwaukeepublicmarket.org/event/weddings",
    phone: "414-336-1111",
    notes: "Strong for rehearsal dinners, brunches, or a smaller reception",
    price: "Not published",
  },
  {
    id: "yacht-club",
    name: "Milwaukee Yacht Club",
    city: "Milwaukee",
    area: "East Side",
    type: "Country club",
    address: "1700 N Lincoln Memorial Dr",
    maxGuests: 200,
    capacity: "About 160–200",
    indoor: "Lakefront clubhouse rooms",
    website: "http://milwaukeeyc.com/",
    phone: "414-271-4455",
    notes: "Members get a rental discount; indoor + waterfront photos",
    price: "Rental $250–$6,000; WeddingWire from ~$1,500",
  },
  {
    id: "atrium",
    name: "The Atrium",
    city: "Shorewood",
    area: "North Shore",
    type: "Industrial loft",
    address: "2107 E Capitol Dr",
    maxGuests: 220,
    capacity: "About 220–230 seated / 300 cocktail",
    indoor: "First-floor ~5,000 sq ft room with glass ceiling",
    website: "https://www.theatriummke.com/",
    phone: "414-902-0065",
    notes: "Rooftop garden is extra; main wedding space is indoor",
    price: "Not published",
  },
  {
    id: "hubbard",
    name: "Hubbard Park Lodge",
    city: "Shorewood",
    area: "North Shore",
    type: "Banquet hall",
    address: "3565 N Morris Blvd",
    maxGuests: 175,
    capacity: "Up to 175",
    indoor: "Year-round wooden lodge with cathedral ceiling and fireplace",
    website: "https://hubbardparklodge.com/",
    phone: "414-332-4207",
    notes: "Milwaukee River setting; in-house catering required",
    price: "Rental $1,500 with $7,000 F&B minimum",
  },
  {
    id: "river-club",
    name: "River Club of Mequon",
    city: "Thiensville",
    area: "North Shore",
    type: "Country club",
    address: "12400 N Ville Du Parc Dr",
    maxGuests: 400,
    capacity: "Directories list 400–500",
    indoor: "9,200 sq ft grand ballroom with floor-to-ceiling windows",
    website: "https://www.riverclubofmequon.com/",
    phone: "",
    notes: "Large North Shore club; indoor ceremony possible",
    price: "Knot from ~$7k; peak WeddingWire often $15k start",
  },
  {
    id: "nscc",
    name: "North Shore Country Club",
    city: "Mequon",
    area: "North Shore",
    type: "Country club",
    address: "3100 W Country Club Dr",
    maxGuests: 250,
    capacity: "Up to 250",
    indoor: "Clubhouse, wine cellar, wood bar; membership not required to host",
    website: "https://www.nscwi.org/",
    phone: "",
    notes: "Private-club feel without requiring membership for the wedding",
    price: "Reception site fee about $12,000 on WeddingWire",
  },
  {
    id: "foxtrot",
    name: "Foxtrot Ballroom (The Annex)",
    city: "Mequon",
    area: "North Shore",
    type: "Banquet hall",
    address: "The Annex, Mequon",
    maxGuests: 120,
    capacity: "Up to 120 seated / 200 cocktail",
    indoor: "Indoor ballroom with terrace and 270-degree Mequon views",
    website: "https://www.zola.com/wedding-vendors/wedding-venues/foxtrot-ballroom",
    phone: "",
    notes: "BYO caterer or use on-site restaurants",
    price: "Zola from $2,500",
  },
  {
    id: "four-points-ns",
    name: "North Shore Ballroom at Four Points",
    city: "Brown Deer",
    area: "North Shore",
    type: "Hotel",
    address: "8900 N Kildeer Ct",
    maxGuests: 320,
    capacity: "North Shore Ballroom ~250; combined Grand Ballroom banquet ~320",
    indoor: "Hotel ballrooms including Crystal for smaller events",
    website: "https://www.marriott.com/en-us/hotels/mkefp-four-points-milwaukee-north-shore/events/",
    phone: "",
    notes: "On-site rooms; in-house F&B required",
    price: "Wedding-Spot from ~$6,147 for 50 guests",
  },
  {
    id: "bavarian",
    name: "The Bavarian Bierhaus",
    city: "Glendale",
    area: "North Shore",
    type: "Banquet hall",
    address: "700 W Lexington Blvd",
    maxGuests: 400,
    capacity: "About 400 seated / 600 standing",
    indoor: "Indoor Bierhall / Festhall",
    website: "https://www.thebavarianbierhaus.com/",
    phone: "414-236-7000",
    notes: "German beer-hall vibe; Old Heidelberg Park on the same campus",
    price: "On request",
  },
  {
    id: "hub-cedar-creek",
    name: "The Hub at Cedar Creek",
    city: "Cedarburg",
    area: "North Shore",
    type: "Banquet hall",
    address: "1814 Washington Ave",
    maxGuests: 200,
    capacity: "Indoor ~200; tent adds more",
    indoor: "6,500+ sq ft indoor plus a permanent tent",
    website: "https://www.thehubatcedarcreek.com/",
    phone: "262-618-4751",
    notes: "On Cedar Creek; in-house catering",
    price: "Not published",
  },
  {
    id: "cedarburg-cc",
    name: "Cedarburg Cultural Center",
    city: "Cedarburg",
    area: "North Shore",
    type: "Historic hall",
    address: "W62 N546 Washington Ave",
    maxGuests: 200,
    capacity: "Indoor dinner about 200–275 with East Gallery",
    indoor: "Founders Room + East Gallery; kitchen for catering",
    website: "https://www.cedarburgculturalcenter.org",
    phone: "262-375-3676",
    notes: "Historic downtown Cedarburg; garden add-on at Kuhefuss House in summer",
    price: "Not published",
  },
  {
    id: "sandhill",
    name: "Sandhill Tree Farm",
    city: "Grafton",
    area: "North Shore",
    type: "Barn",
    address: "2323 E River Rd",
    maxGuests: 200,
    capacity: "About 200 sit-down",
    indoor: "Historic barn on 75 acres with river and pond",
    website: "https://www.sandhilltreefarmwi.com/",
    phone: "",
    notes: "Indoor barn reception with outdoor grounds for photos",
    price: "Knot from $6,500",
  },
  {
    id: "memories",
    name: "Memories Ballroom",
    city: "Port Washington",
    area: "North Shore",
    type: "Historic hall",
    address: "1077 Lake Dr",
    maxGuests: 400,
    capacity: "Main hall up to 400",
    indoor: "1934 dance hall with maple floor, log ceilings, stone fireplaces",
    website: "https://www.memoriesballroom.com/",
    phone: "",
    notes: "Fully indoor ceremony + reception; in-house kitchen",
    price: "Package pricing on site / Knot",
  },
  {
    id: "edison-hall",
    name: "Edison Hall",
    city: "Port Washington",
    area: "North Shore",
    type: "Banquet hall",
    address: "305 E Washington St",
    maxGuests: 400,
    capacity: "Up to 400 sit-down",
    indoor: "Indoor hall with marina views",
    website: "https://edisonhall.com/",
    phone: "262-208-4255",
    notes: "Paramount Records historic site; in-house catering",
    price: "Not published",
  },
  {
    id: "shullys",
    name: "The Watermark at Shully’s",
    city: "Thiensville",
    area: "North Shore",
    type: "Banquet hall",
    address: "146 Green Bay Rd",
    maxGuests: 300,
    capacity: "250–300",
    indoor: "Indoor Ozaukee County event hall",
    website: "https://www.shullyscuisine.com/",
    phone: "262-242-6633",
    notes: "Long-running North Shore banquet venue",
    price: "Entrees $30–$75; 18% service",
  },
  {
    id: "barn-bog",
    name: "The Barn at The Bog",
    city: "Saukville",
    area: "North Shore",
    type: "Barn",
    address: "The Bog golf club, Saukville",
    maxGuests: 325,
    capacity: "Up to 325",
    indoor: "Year-round barn-style event center at a golf club",
    website: "https://www.thebarnatthebog.com/",
    phone: "",
    notes: "About 25 minutes north of Milwaukee",
    price: "WeddingWire from ~$10,500",
  },
  {
    id: "schlitz-audubon",
    name: "Schlitz Audubon Nature Center",
    city: "Bayside",
    area: "North Shore",
    type: "Brewery / unique",
    address: "1111 E Brown Deer Rd",
    maxGuests: 220,
    capacity: "About 220–250",
    indoor: "Indoor nature-center spaces plus Lake Michigan grounds",
    website: "https://www.schlitzaudubon.org/",
    phone: "414-352-2880",
    notes: "Indoor rooms exist; much of the look is nature/lakefront",
    price: "Rental $3,750–$5,000",
  },
  {
    id: "ingleside",
    name: "The Ingleside Hotel",
    city: "Pewaukee",
    area: "Waukesha County",
    type: "Hotel",
    address: "2810 Golf Rd",
    maxGuests: 500,
    capacity: "Lake Country Ballroom sit-down ~500; cocktail 700",
    indoor: "7,200 sq ft Lake Country Ballroom; nine event spaces",
    website: "https://www.theinglesidehotel.com/lake-country-ballroom",
    phone: "262-547-0201",
    notes: "On-site lodging; indoor ceremony plus outdoor gazebo",
    price: "Ballroom F&B minimum $16,000; entrees $28–$42",
  },
  {
    id: "sheraton-brookfield",
    name: "Sheraton Milwaukee Brookfield",
    city: "Brookfield",
    area: "Waukesha County",
    type: "Hotel",
    address: "375 S Moorland Rd",
    maxGuests: 600,
    capacity: "Brookfield Ballroom banquet 600 / reception 900",
    indoor: "Large renovated hotel ballrooms (~18–20k sq ft total)",
    website: "https://www.marriott.com/en-us/hotels/mkesi-sheraton-milwaukee-brookfield-hotel/events/",
    phone: "262-364-1009",
    notes: "Easy guest lodging and parking",
    price: "Packages often $35–$85 per person",
  },
  {
    id: "doubletree-brookfield",
    name: "DoubleTree by Hilton Milwaukee-Brookfield",
    city: "Brookfield",
    area: "Waukesha County",
    type: "Hotel",
    address: "Brookfield",
    maxGuests: 150,
    capacity: "Up to 150",
    indoor: "Hotel ballroom; outdoor ceremony also listed",
    website: "https://www.hilton.com/en/hotels/mkebrdt-doubletree-milwaukee-brookfield/",
    phone: "",
    notes: "Smaller suburban hotel wedding",
    price: "WeddingWire from $3,000",
  },
  {
    id: "courthouse-1893",
    name: "Historic Courthouse 1893",
    city: "Waukesha",
    area: "Waukesha County",
    type: "Historic hall",
    address: "916 N East Ave",
    maxGuests: 300,
    capacity: "Up to 300 sit-down / 450 cocktail",
    indoor: "Two-level Romanesque courthouse, 25-ft ceilings, 12,000+ sq ft",
    website: "https://www.courthouse1893.com/",
    phone: "262-574-9170",
    notes: "Chef Jack’s exclusive catering; fully indoor",
    price: "Knot from $3,000",
  },
  {
    id: "rotunda",
    name: "The Rotunda",
    city: "Waukesha",
    area: "Waukesha County",
    type: "Banquet hall",
    address: "235 W Broadway",
    maxGuests: 200,
    capacity: "200 sit-down / 250 cocktail",
    indoor: "Indoor reception hall",
    website: "https://www.therotundavenue.com",
    phone: "414-364-3761",
    notes: "Downtown Waukesha",
    price: "Not published",
  },
  {
    id: "tuscan-hall",
    name: "Tuscan Hall Venue and Catering",
    city: "Waukesha",
    area: "Waukesha County",
    type: "Banquet hall",
    address: "409 Delafield St",
    maxGuests: 225,
    capacity: "Up to 225",
    indoor: "Indoor banquet hall with in-house catering",
    website: "https://www.tuscanhallwi.com",
    phone: "262-292-1322",
    notes: "About 30 minutes from downtown Milwaukee",
    price: "WeddingWire from $5,000",
  },
  {
    id: "lilac-acres",
    name: "Lilac Acres",
    city: "Waukesha",
    area: "Waukesha County",
    type: "Barn",
    address: "S47W23045 Lawnsdale Rd",
    maxGuests: 175,
    capacity: "150–175",
    indoor: "Indoor ceremony barn plus indoor reception hall",
    website: "https://www.lilacacres.com/",
    phone: "",
    notes: "Flat rental; overnight stay in the event house; wheelchair-friendly reception barn",
    price: "Knot from ~$4,200",
  },
  {
    id: "western-lakes",
    name: "Western Lakes Golf Club",
    city: "Pewaukee",
    area: "Waukesha County",
    type: "Country club",
    address: "W287 N1963 Oakton Rd",
    maxGuests: 300,
    capacity: "About 250–300 (some lists 350)",
    indoor: "Indoor ballroom with course views; indoor or outdoor ceremony",
    website: "https://westernlakes.com/weddings-and-events/",
    phone: "262-547-9447",
    notes: "Zilli Hospitality on current club pages",
    price: "Rental $500–$1,500; entrees $34–$55",
  },
  {
    id: "merrill-hills",
    name: "The Legend at Merrill Hills",
    city: "Waukesha",
    area: "Waukesha County",
    type: "Country club",
    address: "W270 S3425 Merrill Hills Rd",
    maxGuests: 300,
    capacity: "Up to 300",
    indoor: "Indoor dining-room receptions; lounge for cocktails",
    website: "https://www.merrillhills.com/",
    phone: "262-968-9717",
    notes: "Outdoor waterfall ceremony with indoor reception",
    price: "Not published",
  },
  {
    id: "muskego-lakes",
    name: "Muskego Lakes Country Club",
    city: "Muskego",
    area: "Waukesha County",
    type: "Country club",
    address: "Muskego",
    maxGuests: 400,
    capacity: "Up to 400",
    indoor: "Two indoor banquet halls",
    website: "https://muskegolakes.com/weddings-receptions/",
    phone: "",
    notes: "Full-service club; micro-wedding option listed",
    price: "WeddingWire from $5,000",
  },
  {
    id: "broadlands",
    name: "Broadlands Golf Club",
    city: "North Prairie",
    area: "Waukesha County",
    type: "Country club",
    address: "Near Waukesha / Mukwonago",
    maxGuests: 250,
    capacity: "Up to 250",
    indoor: "Ballroom with 20-ft vaulted ceiling and built-in dance floor",
    website: "https://www.broadlandsgolfclub.com/banquets-weddings",
    phone: "262-470-8661",
    notes: "Indoor reception; outdoor ceremony locations",
    price: "Packages described as affordable; ask for current menu",
  },
  {
    id: "wisconsin-club-cc",
    name: "Wisconsin Club – Country Club",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Country club",
    address: "6200 W Good Hope Rd",
    maxGuests: 250,
    capacity: "Ballroom up to 250",
    indoor: "Indoor ballroom and Oak Room; garden add-on",
    website: "https://wisconsinclub.com/",
    phone: "",
    notes: "Different property from the downtown Wisconsin Club",
    price: "WeddingWire from $3,500",
  },
  {
    id: "davians",
    name: "Davians Catering & Events",
    city: "Menomonee Falls",
    area: "Waukesha County",
    type: "Banquet hall",
    address: "N56 W16300 Silver Spring Dr",
    maxGuests: 240,
    capacity: "Up to 240",
    indoor: "Suburban banquet facility with in-house catering",
    website: "http://davians.com/",
    phone: "262-781-3333",
    notes: "Long-running Waukesha County banquet option",
    price: "Rental $3,500–$11,000; entrees $25–$96",
  },
  {
    id: "wilson-center",
    name: "Sharon Lynne Wilson Center",
    city: "Brookfield",
    area: "Waukesha County",
    type: "Historic hall",
    address: "Brookfield",
    maxGuests: 600,
    capacity: "100–600 depending on rooms",
    indoor: "Arts-center indoor spaces",
    website: "https://wilson-center.com/",
    phone: "",
    notes: "Useful if you want a performance-hall feel in Brookfield",
    price: "Rental about $6,000",
  },
  {
    id: "sonesta-west",
    name: "Sonesta Milwaukee West",
    city: "Wauwatosa",
    area: "West Milwaukee",
    type: "Hotel",
    address: "10499 W Innovation Dr",
    maxGuests: 400,
    capacity: "Up to 400",
    indoor: "West-side hotel ballroom",
    website: "https://www.sonesta.com/",
    phone: "414-475-9500",
    notes: "Practical hotel wedding with parking",
    price: "Entrees $25–$50; 21% service",
  },
  {
    id: "hgi-park-place",
    name: "Hilton Garden Inn (Park Place)",
    city: "Milwaukee",
    area: "West Milwaukee",
    type: "Hotel",
    address: "11600 W Park Pl",
    maxGuests: 600,
    capacity: "Up to 600",
    indoor: "Large west-side hotel event space",
    website: "https://www.hilton.com/",
    phone: "414-359-9823",
    notes: "High indoor capacity near the Mayfair / Park Place area",
    price: "On request; 20% service",
  },
  {
    id: "delafield-hotel",
    name: "The Delafield Hotel",
    city: "Delafield",
    area: "Lake Country",
    type: "Hotel",
    address: "415 Genesee St",
    maxGuests: 250,
    capacity: "Up to 250 seated / 300 standing",
    indoor: "Three indoor event spaces in a boutique hotel",
    website: "https://www.thedelafieldhotel.com/delafield-weddings",
    phone: "262-346-9311",
    notes: "38 rooms on site; event manager included",
    price: "Zola full-wedding from ~$10–12k; 23% service",
  },
  {
    id: "carriage-house",
    name: "Carriage House at Lac La Belle",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Barn",
    address: "6996 Pennsylvania St",
    maxGuests: 240,
    capacity: "Indoor banquet about 240",
    indoor: "Barn-style hall with beams and floor-to-ceiling windows",
    website: "https://carriagehouseatlaclabelle.com",
    phone: "262-567-7833",
    notes: "At The Club at Lac La Belle; in-house catering required",
    price: "Knot from $3,500; couples often spend ~$25k all-in",
  },
  {
    id: "1896-room",
    name: "1896 Room at Lac La Belle",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Country club",
    address: "6996 Pennsylvania St",
    maxGuests: 190,
    capacity: "About 160–190 seated",
    indoor: "Remodeled clubhouse ballroom overlooking the 18th green",
    website: "https://www.theknot.com/marketplace/1896-room-at-lac-la-belle-oconomowoc-wi-2011760",
    phone: "262-567-7833",
    notes: "Same property as Carriage House, different room",
    price: "Flat-rate room rental; ask current package",
  },
  {
    id: "oconomowoc-lake-club",
    name: "Oconomowoc Lake Club",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Country club",
    address: "4668 Lake Club Circle",
    maxGuests: 200,
    capacity: "Up to 200",
    indoor: "Great Hall with cathedral ceilings and 24-ft bar; Commodore Room upstairs",
    website: "https://oconomowoclakeclub.org/weddings-at-olc/",
    phone: "",
    notes: "Lakefront; in-house F&B required; amplified music indoors only",
    price: "Directory figures conflict; tour for a real quote",
  },
  {
    id: "occ",
    name: "Oconomowoc Community Center",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Banquet hall",
    address: "220 W Wisconsin Ave",
    maxGuests: 200,
    capacity: "About 200–230",
    indoor: "Upper hall with vaulted ceilings, hardwood, catering kitchen",
    website: "https://www.oconomowoc-wi.gov/",
    phone: "",
    notes: "Lac La Belle waterfront; outside caterers permitted",
    price: "WeddingWire from $2,500",
  },
  {
    id: "valerie",
    name: "The Valerie",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Banquet hall",
    address: "Pabst Farms / next to Staybridge Suites",
    maxGuests: 400,
    capacity: "Up to 400",
    indoor: "13,000 sq ft indoor wedding venue",
    website: "https://thevaleriewi.com/",
    phone: "",
    notes: "Hotel next door at Staybridge Suites",
    price: "WeddingWire from $3,000",
  },
  {
    id: "rustic-manor",
    name: "Rustic Manor 1848",
    city: "Hartland",
    area: "Lake Country",
    type: "Barn",
    address: "3115 State Road 83",
    maxGuests: 275,
    capacity: "50–275",
    indoor: "Heated and air-conditioned barn; indoor ceremony under the beams",
    website: "https://www.rusticmanor1848.com/",
    phone: "262-224-0316",
    notes: "Year-round indoor barn; 12 acres; two bridal suites",
    price: "Rental $3,200–$6,700 by day/date",
  },
  {
    id: "cupola-barn",
    name: "Cupola Barn",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Barn",
    address: "N88 W35490 Mapleton Rd",
    maxGuests: 200,
    capacity: "Up to 200",
    indoor: "1840s indoor barn; heaters added for cooler weather",
    website: "https://www.theknot.com/marketplace/cupola-barn-oconomowoc-wi-1046326",
    phone: "",
    notes: "BYO caterer and bar; reviews note rustic amenities (confirm restrooms/water on tour)",
    price: "Knot estimate ~$5,600",
  },
  {
    id: "trinity-peak",
    name: "Barn at Trinity Peak",
    city: "Oconomowoc",
    area: "Lake Country",
    type: "Barn",
    address: "N80W38726 McMahon Rd",
    maxGuests: 200,
    capacity: "Up to 200",
    indoor: "Renovated 1934 dairy barn",
    website: "https://milwaukeewiweddingvenues.com/venues/barn-at-trinity-peak/",
    phone: "262-955-8080",
    notes: "Seasonal: typically May to mid-November",
    price: "Knot from ~$3,500",
  },
  {
    id: "embers",
    name: "Embers of Tuscany",
    city: "Ixonia",
    area: "Lake Country",
    type: "Historic hall",
    address: "Ixonia (between Milwaukee and Madison)",
    maxGuests: 320,
    capacity: "Seating up to 320",
    indoor: "Restored historic indoor ballroom with two bars",
    website: "https://embersoftuscany.com/",
    phone: "262-354-4848",
    notes: "Open vendor list; paved parking",
    price: "Varies by season and day",
  },
  {
    id: "red-circle",
    name: "Red Circle Inn",
    city: "Nashotah",
    area: "Lake Country",
    type: "Banquet hall",
    address: "Nashotah",
    maxGuests: 240,
    capacity: "Up to 240",
    indoor: "Historic restaurant / inn (Wisconsin’s oldest restaurant)",
    website: "https://redcircleinn.com/",
    phone: "",
    notes: "Indoor + outdoor listed; confirm indoor reception layout on tour",
    price: "WeddingWire from $5,800",
  },
  {
    id: "commodore",
    name: "The Commodore (Bartolotta)",
    city: "Hartland",
    area: "Lake Country",
    type: "Banquet hall",
    address: "1807 Nagawicka Rd",
    maxGuests: 220,
    capacity: "220 seated / 250 standing",
    indoor: "Historic waterfront restaurant (opened 1902)",
    website: "http://thecommodoredelafield.com/",
    phone: "262-563-8070",
    notes: "Nagawicka Lake; Bartolotta group",
    price: "On request",
  },
  {
    id: "delafield-brewhaus",
    name: "Delafield Brewhaus",
    city: "Delafield",
    area: "Lake Country",
    type: "Brewery / unique",
    address: "3832 Hillside Dr",
    maxGuests: 200,
    capacity: "Up to 200",
    indoor: "Brewery hall with patio ceremony option",
    website: "http://delafieldbrewhaus.com/",
    phone: "262-646-7821",
    notes: "Casual brewery wedding between Milwaukee and Madison",
    price: "WeddingWire from $5,000; entrees $16–$40",
  },
  {
    id: "fete",
    name: "fête",
    city: "Wales",
    area: "Lake Country",
    type: "Barn",
    address: "500 E Summit Ave",
    maxGuests: 300,
    capacity: "Up to 300",
    indoor: "Modern-rustic indoor venue",
    website: "https://feteofwales.com",
    phone: "262-528-3383",
    notes: "Outside caterers permitted",
    price: "Not published",
  },
  {
    id: "chandelier",
    name: "Chandelier Ballroom",
    city: "Hartford",
    area: "North Shore",
    type: "Historic hall",
    address: "150 Jefferson Ave",
    maxGuests: 500,
    capacity: "Great Hall 150–500; Fireside Room up to 100 reception",
    indoor: "1928 octagonal Great Hall; indoor ceremonies in Fireside or Great Hall",
    website: "https://www.chandelierballroom.com/venue-info/",
    phone: "262-673-4946",
    notes: "One-ton Art Deco chandelier; ADA one-level; ~400 parking spaces",
    price: "Great Hall Sat $4,900 / Fri $3,900 / Sun–Thu $2,900",
  },
  {
    id: "terrace-167",
    name: "Terrace 167",
    city: "Richfield",
    area: "North Shore",
    type: "Barn",
    address: "3210 Hwy 167",
    maxGuests: 350,
    capacity: "Up to 350",
    indoor: "Modern-rustic indoor venue in Washington County",
    website: "https://terrace167.com",
    phone: "262-623-6588",
    notes: "Outside caterers permitted",
    price: "Not published",
  },
  {
    id: "foundry-45",
    name: "Foundry 45",
    city: "Kewaskum",
    area: "North Shore",
    type: "Industrial loft",
    address: "9480 US Hwy 45",
    maxGuests: 350,
    capacity: "Up to 350",
    indoor: "Indoor rustic / industrial event venue",
    website: "https://foundry45.com/",
    phone: "262-808-6020",
    notes: "Farther north (~45–50 min); distinctive industrial look",
    price: "Rental $5,500–$8,250",
  },
  {
    id: "farm-dover",
    name: "The Farm at Dover",
    city: "Kansasville",
    area: "South / Racine",
    type: "Barn",
    address: "26060 Washington Ave, Dover",
    maxGuests: 170,
    capacity: "About 160–170",
    indoor: "Renovated 4,300 sq ft two-story barn; indoor ceremony backup",
    website: "https://www.thefarmatdover.com/",
    phone: "773-802-6351",
    notes: "About 35 miles SW of Milwaukee; Victorian bridal house on site",
    price: "2027 Sat $8,000 / Fri $7,200 / Sun $6,200",
  },
  {
    id: "stein-farms",
    name: "Stein Farms",
    city: "Salem",
    area: "South / Racine",
    type: "Barn",
    address: "5708 312th Ave",
    maxGuests: 230,
    capacity: "Barn 50–230",
    indoor: "Indoor barn plus indoor Lodge with dance floor, bar, fireplace",
    website: "https://steinfarms.com/",
    phone: "",
    notes: "Between Kenosha and Lake Geneva",
    price: "Custom packages; dollars not on fetched pages",
  },
  {
    id: "wagon-wheel",
    name: "The Barn at Wagon Wheel Farm",
    city: "Burlington",
    area: "South / Racine",
    type: "Barn",
    address: "5264 Warren Rd",
    maxGuests: 200,
    capacity: "Not clearly published; restored barn on 100 acres",
    indoor: "Restored 18th-century barn with modern amenities",
    website: "https://www.wagonwheelbarn.com/",
    phone: "",
    notes: "May–October; one wedding per weekend; ~50 min from Milwaukee",
    price: "Not published",
  },
  {
    id: "mercantile",
    name: "Mercantile Hall",
    city: "Burlington",
    area: "South / Racine",
    type: "Historic hall",
    address: "425 N Pine St",
    maxGuests: 250,
    capacity: "Up to 250",
    indoor: "Historic indoor hall near Lake Geneva",
    website: "http://mercantilehall.com/",
    phone: "262-758-6280",
    notes: "Downtown Burlington",
    price: "Rental $1,495–$7,295",
  },
  {
    id: "dekoven",
    name: "DeKoven Center",
    city: "Racine",
    area: "South / Racine",
    type: "Historic hall",
    address: "2000 Wisconsin Ave",
    maxGuests: 225,
    capacity: "Up to 225",
    indoor: "Historic campus indoor spaces",
    website: "https://dekovencenter.org/",
    phone: "262-633-6401",
    notes: "Racine historic retreat campus",
    price: "Rental $3,900–$4,750",
  },
  {
    id: "hotel-verdant",
    name: "Hotel Verdant",
    city: "Racine",
    area: "South / Racine",
    type: "Hotel",
    address: "500 Main St",
    maxGuests: 125,
    capacity: "Up to 125",
    indoor: "Boutique hotel event space",
    website: "https://www.hotelverdant.com/",
    phone: "262-456-6851",
    notes: "Smaller lakefront-city hotel wedding",
    price: "On request",
  },
  {
    id: "roma-lodge",
    name: "Roma Lodge",
    city: "Racine",
    area: "South / Racine",
    type: "Banquet hall",
    address: "Racine",
    maxGuests: 300,
    capacity: "Up to 300",
    indoor: "Indoor hall (outdoor also listed)",
    website: "https://romalodge.com/",
    phone: "",
    notes: "Traditional banquet lodge serving the Milwaukee area since the 1950s",
    price: "WeddingWire from $4,650",
  },
  {
    id: "crowne-airport",
    name: "Crowne Plaza Milwaukee Airport",
    city: "Milwaukee",
    area: "South / Racine",
    type: "Hotel",
    address: "6401 S 13th St",
    maxGuests: 400,
    capacity: "Mag lists up to 1,500 for the hotel; typical wedding rooms are smaller",
    indoor: "Airport-area hotel ballrooms",
    website: "https://www.ihg.com/",
    phone: "414-563-4070",
    notes: "Practical if many guests fly in",
    price: "Entrees $35–$65; 21% service",
  },
  {
    id: "grand-geneva",
    name: "Grand Geneva Resort & Spa",
    city: "Lake Geneva",
    area: "Lake Geneva",
    type: "Hotel",
    address: "Lake Geneva",
    maxGuests: 400,
    capacity: "Evergreen 230; Maple Lawn 250; Grand Ballroom 400; Chalet 160",
    indoor: "Multiple indoor ballrooms; skip the outdoor-only Pavilion if you need indoor",
    website: "https://www.grandgeneva.com/weddings/venues",
    phone: "",
    notes: "Destination resort ~1 hour from Milwaukee; rooms on site",
    price: "On request",
  },
  {
    id: "cove-lg",
    name: "The Cove of Lake Geneva",
    city: "Lake Geneva",
    area: "Lake Geneva",
    type: "Hotel",
    address: "111 Center St",
    maxGuests: 220,
    capacity: "About 220–250 across spaces; min 60",
    indoor: "Promenade ballroom with cathedral ceilings; Lakeshore Room for smaller events",
    website: "https://www.coveoflakegeneva.com/",
    phone: "262-249-9460",
    notes: "Waterfront hotel; indoor reception after a shoreline ceremony if you want both",
    price: "Reception site fee $6,000",
  },
  {
    id: "geneva-national",
    name: "Geneva National Resort",
    city: "Lake Geneva",
    area: "Lake Geneva",
    type: "Country club",
    address: "Lake Geneva / Lake Como",
    maxGuests: 280,
    capacity: "Grand Ballroom 280; Legends Room 160",
    indoor: "Clubhouse Grand Ballroom with a 90-ft window wall; Legends Room 4,200 sq ft",
    website: "https://www.destinationgn.com/grand-ballroom",
    phone: "262-245-7000",
    notes: "Fairway and Lake Como views",
    price: "Not published",
  },
  {
    id: "baker-house",
    name: "Baker House 1885",
    city: "Lake Geneva",
    area: "Lake Geneva",
    type: "Museum / mansion",
    address: "327 Wrigley Dr",
    maxGuests: 100,
    capacity: "House comfortably ~100; gardens add more",
    indoor: "Gilded Age mansion parlors, restaurant, speakeasy",
    website: "https://bakerhouse1885.com/private-events/",
    phone: "262-248-4700",
    notes: "Indoor reception is the house; gardens are extra and more weather-exposed",
    price: "First floor + garden $4k–$6k; whole house two nights $21k",
  },
  {
    id: "hawks-view",
    name: "Hawk’s View Golf Club",
    city: "Lake Geneva",
    area: "Lake Geneva",
    type: "Country club",
    address: "7377 Krueger Rd",
    maxGuests: 280,
    capacity: "280–350 depending on source",
    indoor: "Indoor club venue",
    website: "https://hawksviewgolfclub.com/",
    phone: "262-348-9900",
    notes: "Bridal suite; outside caterers not permitted",
    price: "On request",
  },
  {
    id: "evergreen-gc",
    name: "Evergreen Golf Club",
    city: "Elkhorn",
    area: "Lake Geneva",
    type: "Country club",
    address: "N6246 US Highway 12",
    maxGuests: 250,
    capacity: "Up to 250 plated / 220 buffet",
    indoor: "Evergreen Room with 15-ft vaulted ceilings (Pavilion is three-season — skip if you need fully indoor)",
    website: "https://www.zola.com/wedding-vendors/wedding-venues/evergreen-golf-club",
    phone: "",
    notes: "Ask specifically for the indoor Evergreen Room",
    price: "Not published",
  },
];
